title: Ukukdin's Tech Blog
description: "LangChain, CS Study, Spring Boot, Infra 기술 블로그"
url: "https://ukukdin.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .idea
  - node_modules
